version: "3.9"

services:
  fresco:
    container_name: fresco
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      # Set envrionment variables based on the .env file
    # Set environment variables directly in the docker-compose file
    # environment:
    #   POSTGRES_ADDR: postgres
    #   POSTGRES_DATABASE: frescodb
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/next-app
    restart: always
    ports:
      - 3000:3000
    networks:
      - fresco_network

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "midshiftDB"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - fresco_network

volumes:
  postgres:
    name: fresco-db

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  fresco_network:
    external: true